services:
  mcp-kaggle-server:
      image: mcp-kaggle-server  
      container_name: mks
      build: .
      ports:
        - "3000:3000"  # Map host port 3000 to container port 3000
      volumes:
        - ./data:/app/data

        # - ./your_config.json:/app/conf/server_config.json:ro # Mount your config read-only
      
      command: ["python", "server.py", "--transport", "sse", "--host", "0.0.0.0", "--port", "3000"]
    
volumes:
  data: